stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging
    - deploy_dev

image: node:latest

before_script:
    - cd ToDoProject
    - npm i
    
cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - npm run build
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
test: 
    stage: test
    script: 
        - npm run test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
deploy_production:
    stage: deploy_production
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == "master"
        
deploy_staging:
    stage: deploy_staging
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == "staging"
    
deploy_dev:
    stage: deploy_dev
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == "development"