stages: 
    - build 
    - test
    - run
    
before_script:
    - cd ToDoProject
    
cache: 
    paths: 
        - build/
    
build:
    image: node:8
    stage: build
    script: 
        - npm i
        - npm run build
        
test: 
    stage: test
    script: 
        - npm run test
        
run: 
    stage: run
    script: 
        - serve -s build