stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging
    - deploy_dev

image: node:latest

before_script:
    - cd ToDoProject
    - npm i
    
cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - npm run build
    only:
        - merge_requests
        
test: 
    stage: test
    script: 
        - npm run test
    only:
        - merge_requests
        
deploy_production:
    stage: deploy_production
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    only:
        - merge_requests
        - master
        
deploy_staging:
    stage: deploy_staging
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    only:
        - merge_requests
        - staging
        
deploy_dev:
    stage: deploy_dev
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    only:
        - merge_requests
        - development