stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging

image: node:latest

cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - cd ToDoProject
        - npm i
        - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
test: 
    stage: test
    dependencies: 
    - build
    script: 
        - cd ToDoProject
        - npm i
        - npm run test
    dependencies: 
        - build
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
deploy_production:
    stage: deploy_production
    environment: production
    dependencies: 
    - build
    image: python:latest
    script:
    - pip install awscli
    - aws s3 cp ./ToDoProject/build/ s3://todo-app-create-react-app/ --recursive
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        
pages:
    stage: deploy_staging
    image: alpine:latest
    environment: staging
    dependencies: 
        - build
    script:
        - mkdir -p ./public
        - cp -r ./ToDoProject/build/. ./public/
    artifacts: 
        paths:
            - public
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'