stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging
    
image: node:latest

variables:
  CI_STAGING_ID: "staging"
  CI_PRODUCTION_ID: "production"

cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - cd ToDoProject
        - npm i
        - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
test: 
    stage: test
    dependencies: 
    - build
    script: 
        - cd ToDoProject
        - npm i
        - npm run test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
pages:
    stage: deploy_production
    environment: production
    image: alpine:latest
    dependencies: 
        - build
    script:
        - mkdir -p ./public/$CI_PRODUCTION_ID
        - cp -r ./ToDoProject/build/. ./public/$CI_PRODUCTION_ID
    artifacts: 
        paths:
            - public
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        
pages:
    stage: deploy_staging
    environment: staging
    image: alpine:latest
    dependencies: 
        - build
    script:
        - mkdir -p ./public/$CI_STAGING_ID
        - cp -r ./ToDoProject/build/. ./public/$CI_STAGING_ID
    artifacts: 
        paths:
            - public
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'