stages: 
    - build 
    - test
    - deploy

image: node:latest

before_script:
    - cd ToDoProject
    - npm i
    
cache: 
    paths: 
        - build/

build:
    stage: build
    script: 
        - npm run build
        
test: 
    stage: test
    script: 
        - npm run test
        
deploy:
    stage: deploy
    script:
    - echo "Deploy app"
    artifacts:
        name: "todo-app"
        paths:
        - build/*