stages: 
    - build 
    - test
    - run

image: node:latest

before_script:
    - cd ToDoProject
    - npm i
    
cache: 
    paths: 
        - build/

build:
    stage: build
    script: 
        - npm run build
        
test: 
    stage: test
    script: 
        - npm run test
        
run: 
    stage: run
    script: 
        - serve -s build