stages: 
    - build 
    - test
    - deploy
    
image: node:latest

cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - cd ToDoProject
        - npm i
        - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
test: 
    stage: test
    dependencies: 
    - build
    script: 
        - cd ToDoProject
        - npm i
        - npm run test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
pages:
    stage: deploy
    environment: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    image: alpine:latest
    dependencies: 
        - build
    script:
        - mkdir -p ./public/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - cp -r ./ToDoProject/build/. ./public/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    artifacts: 
        paths:
            - public
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'