stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging
    - deploy_dev

image: node:latest

cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - cd ToDoProject
        - npm i
        - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
        
test: 
    stage: test
    script: 
        - cd ToDoProject
        - npm i
        - npm run test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
deploy_production:
    stage: deploy_production
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        
deploy_staging:
    stage: deploy_staging
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'

variables:
  AWS_ACCESS_KEY_ID: "AKIASBYVMTEK4QR6WHAJ"
  AWS_SECRET_ACCESS_KEY: “216upSNmzw89oz/ppRa5kEKCBzTEBoNk6pmqqVF3”

deploy_dev:
    stage: deploy_dev
    dependencies: 
    - build
    image: python:latest
    script:
    - pip install awscli
    - aws s3 cp ./build/ s3://todo-app-create-react-app/ --recursive --exclude "*" --include "*.html"
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*