stages: 
    - build 
    - test
    - deploy_production
    - deploy_staging
    - deploy_dev
    - pages

image: node:latest

before_script:
    - cd ToDoProject
    - npm i
    
cache: 
    paths: 
        - ToDoProject/build/

build:
    stage: build
    script: 
        - npm run build
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  image: alpine:latest
  script:
  - mkdir -p ./public
  - cp ToDoProject/build/* ./public/
  artifacts:
    paths:
    - public
  except:
    - master
        
test: 
    stage: test
    script: 
        - npm run test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        
deploy_production:
    stage: deploy_production
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        
deploy_staging:
    stage: deploy_staging
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
    
deploy_dev:
    stage: deploy_dev
    script:
    - npm run build
    artifacts:
        name: "todo-app"
        paths:
        - ToDoProject/build/*
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"'